# Generated by Django 2.2.8 on 2019-12-17 10:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
